POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MzEwNzg5MDcsInVzZXJJZCI6MX0.sBSokqqMpfc1_7U4qs0GVdblvaoi_m3oOrVQ8ioEZEU

{
    "name":"New Test event! ",
    "description": "A new test event descr!",
    "location": "a test location!",
    "dateTime": "2024-12-30T12:40:00.00Z"
}
