POST http://localhost:8080/events
Content-Type: application/json

{
    "name":"Test event 6",
    "description": "A test event descr 6",
    "location": "a test location 6",
    "dateTime": "2024-12-17T12:40:00.00Z"
}
